### ISSUE TITLE
Unkown Color FC

### ISSUE THREAD

**Issue by GermainZ** [MohammadAG/Xposed-Tinted-Status-Bar#10]
Logcat: http://bpaste.net/show/am4F4pNDGcncwvQFCG5j/

**Comment by GermainZ** [comment]
This is the culprit:
`<string name="pref_default_status_bar_icon_tint">cff0000</string>`

The preference got saved without being an actual color (7 letters instead of 8.)

**Comment by MohammadAG** [comment]
Apparently, I don't check colours before saving, only when previewing, so it's your fault for not clicking preview first.

Fixed as per https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/7e0fe7878399435ea72a1dae3892ab519235d795 :)
