### ISSUE TITLE
Logcat flooding with TSB errors

### ISSUE THREAD

**Issue by Avamander** [MohammadAG/Xposed-Tinted-Status-Bar#100]
For some reason TSB creates a huge amount of errors. I would be really happy if logcat would not be flooded with TSB errors.
Device: LG D605
ROM: CM11 release 7 by Varcain
Log:
https://www.dropbox.com/s/sqmb2ww2e0lr4ol/Log_2014-08-20_00-44-48.txt

**Comment by GermainZ** [comment]
Disable debug mode.

**Comment by Avamander** [comment]
That's the thing, it is disabled.

**Comment by GermainZ** [comment]
You've removed your log, I can't view it anymore.

**Comment by Avamander** [comment]
@GermainZ I am so sorry, I accidentally removed the log from my dropbox. I restored the log.

**Comment by GermainZ** [comment]
Yeah, debug mode (TSB settings > Debug mode) is definitely turned on (I'm assuming you're using the latest version, 1.8.9.3). Closing this since it's not an issue.
