### ISSUE TITLE
Icons shouldn't be inverted with these colors

### ISSUE THREAD

**Issue by fgsfds** [MohammadAG/Xposed-Tinted-Status-Bar#122]
![screenshot_2014-09-25-19-20-23](https://cloud.githubusercontent.com/assets/4870330/4406878/ff5769e0-44c5-11e4-9423-2d20804b0114.png)

It's AppDeals and Microsoft Office.

**Comment by AbFarid** [comment]
Try increasing "Max HS[V] for black icons" option, that helps in some cases.

**Comment by fgsfds** [comment]
Increased it to the maximum, still black in Office.

**Comment by AbFarid** [comment]
Yeah, I think it works in Excel, but not Word, not complete fix, thus "some cases".
