### ISSUE TITLE
Wrong status bar color in Chrome

### ISSUE THREAD

**Issue by fgsfds** [MohammadAG/Xposed-Tinted-Status-Bar#123]
Status bar color differs from Chome's action bar.

![screenshot_2014-09-25-20-03-55](https://cloud.githubusercontent.com/assets/4870330/4406952/9590ea80-44c6-11e4-8c6b-5f36b2282496.png)

**Comment by AbFarid** [comment]
Try installing the additional plug-in if you're on latest version, it will also change color in incognito mode. Otherwise, try fff3f3f3 as manual tint color.
