### ISSUE TITLE
Bug when installing and uninstalling apps from Play

### ISSUE THREAD

**Issue by fgsfds** [MohammadAG/Xposed-Tinted-Status-Bar#125]
When you install or uninstall an app from Play in background and another app is currently on the foreground, ones the app is installed, the status bar color changes to Play's color.

https://www.youtube.com/watch?v=C6UYP_DMY4c

**Comment by AbFarid** [comment]
Doesn't occur on my phone. Perhaps a rom thing?

**Comment by fgsfds** [comment]
It's stock LG G2, 4.4.2 if it does matter.

**Comment by AbFarid** [comment]
How about the TSB version? Mine is 1.8.9.5

**Comment by fgsfds** [comment]
Same.

**Comment by Nxt3** [comment]
I have the same issue--thought it was just me.

Stock, 4.4.2 MotoX
&&
Stock, 4.4.4 Nexus 7 (2013)
