### ISSUE TITLE
glitch on notification icon

### ISSUE THREAD

**Issue by enjoyfreedom** [MohammadAG/Xposed-Tinted-Status-Bar#127]
Hi, i'm experiencing a glitch with the left icons of the status bar,the notification ones, they all merge in one flashy arrowshaped icon (i can't explain better) it disappears in about a minute but it's a bit annoying... Running on HTC One M7

**Comment by GermainZ** [comment]
This doesn't seem to be related to TSB, since TSB doesn't "merge" icons. If this happens with **only** TSB enabled, please open a new issue and include a screenshot.
