### ISSUE TITLE
Navigation Bar Icon Tint Work-around for Stock ROMs

### ISSUE THREAD

**Issue by zst123** [MohammadAG/Xposed-Tinted-Status-Bar#13]
Like you said in this commit https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/0091b7501441c5dc9297567f59d01a26d893d35c , some stock roms also remove AOSP methods. In my ROM, even the names of the tags are different and nav bar icon tinting didn't work. I have come up with a work-around although it is a little slow.

I modified this method

```
private void setNavigationBarIconTint(final int tintColor) {
        if (mNavigationBarView == null)
            return;
        tintImageViews(mNavigationBarView, tintColor);
    }
```

and then added a new method

```
    private void tintImageViews(ViewGroup group, int tintColor) {
        for (int i = 0; i < group.getChildCount(); i++) {
            View view = group.getChildAt(i);
            if (view == null) {
                continue;
            } else if (view instanceof ImageView) {
                ((ImageView)view).setColorFilter(tintColor,
                        mSettingsHelper.getNotificationIconCfType());
            } else if (view instanceof ViewGroup){
                tintImageViews((ViewGroup) view, tintColor);
            }
        }
    }

```

I think this will useful as a backup/fallback method

**Comment by MohammadAG** [comment]
How slow is slow? We wouldn't want users with ROMs that don't change names to complain about lag

**Comment by zst123** [comment]
Depending on how many ViewGroup's the ROM has for the navigation bar. It shouldn't impact so much. (maybe a hundred milliseconds) Maybe you could add it as an option in the settings. Something like "Mode to modify Nav Bar".
1)Default (less compatible but faster)
2)Recursive(more compatible but slower)
