### ISSUE TITLE
Bug: Keyboard pops up twice

### ISSUE THREAD

**Issue by sumeshmeena** [MohammadAG/Xposed-Tinted-Status-Bar#131]
Whenever I select an input box, the keyboard pops up twice. It pops up, then goes down then again pops up. Please figure this out.

**Comment by Nxt3** [comment]
This has <b>nothing</b> to do with Tinted Status Bar.

**Comment by sumeshmeena** [comment]
It happens only when Tinted Status Bar is enabled. I've tested it many
times.

Sumesh Meena

**Comment by Nxt3** [comment]
Then you'd need to give a ton more information than that.

What keyboard?
What version of Android?
What phone?
What ROM?

**Comment by sumeshmeena** [comment]
Google Keyboard, Android Keyboard
Android Version 4.2.1
Xolo Q800-X edition
Stock Rom but highly modified using xposed,etc

Sumesh Meena

**Comment by Nxt3** [comment]
Disable all Xposed modules except for Tinted Status Bar.

**Comment by sumeshmeena** [comment]
Ok. It works well now. Now what to do.

Sumesh Meena

**Comment by sumeshmeena** [comment]
How to find which module is causing that.

Sumesh Meena

**Comment by Nxt3** [comment]
Enable a module one-by-one and test to see if it works.
Keep Tinted StatusBar enabled.

<b>Steps</b>
1.) Enable a <i>single</i> module, then reboot.
2.) Test keyboard.
3.) Repeat until the issue arises.

**Comment by sumeshmeena** [comment]
Its Gravity Box[JB]

Sumesh Meena
