### ISSUE TITLE
System user interface crashes

### ISSUE THREAD

**Issue by Avamander** [MohammadAG/Xposed-Tinted-Status-Bar#132]
Device: LG D605
Software: CM 11
Debug mode: No
Bug:
System UI crashes throws me at lockscreen, happens randomly.

XPosed log:
https://www.dropbox.com/s/6qbpq0jvu318chm/xposed_error_20141019_173437.log?dl=0

**Comment by GermainZ** [comment]
The Xposed log is useless, please upload a normal logcat filtered for _AndroidRuntime_.

**Comment by Avamander** [comment]
Do you have any ideas how I could do that without running a app in background? Background services often get killed if I play a game on my device. Also, the crash happens randomly so I can't just open an app and collect the log, I have to wait for it to happen.

**Comment by GermainZ** [comment]
You can wait for the crash to happen then take a logcat within 1-2 minutes.
