### ISSUE TITLE
will we get new update on google play store tinted status bar?

### ISSUE THREAD

**Issue by bradjyoon** [MohammadAG/Xposed-Tinted-Status-Bar#139]
So reacently I got new google play store and got whole material design however what I noticed is that tinted status bar no longer works on google play store. Will you guys please update that a soon as possible?

**Comment by bradjyoon** [comment]
I'm talking about status bar. And I have galaxy s4 build number ends with NG6

**Comment by GermainZ** [comment]
Duplicate of #129.
