### ISSUE TITLE
Android Lollipop action bar apps

### ISSUE THREAD

**Issue by dancojocaru2000** [MohammadAG/Xposed-Tinted-Status-Bar#144]
On apps with action bar based on Android Lollipop, the statusbar is always black, even when using per app settings. For example, Gmail and Messenger backport. Please solve!

**Comment by GermainZ** [comment]
Duplicate of #129.

**Comment by trell2016** [comment]
But is #129 fixed

**Comment by GermainZ** [comment]
For the Play Store alone (a particular example of #129), a solution is given. The issue in general is still open (which is why it's not a closed issue ;)).

**Comment by dancojocaru2000** [comment]
#129 is only about Google Play. I say for all Material apps (almost all, Textra SMS works). Try on Gmail app

**Comment by dancojocaru2000** [comment]
Ok, now I got it. Thanks!
