### ISSUE TITLE
Can't uninstall or disable

### ISSUE THREAD

**Issue by brpqzme** [MohammadAG/Xposed-Tinted-Status-Bar#18]
There seems to be no way to disable this module. I've disabled it from xposed AND uninstalled it, but it still keeps changing the status bar tint. What can be done?

**Comment by GermainZ** [comment]
Reboot.
On Sun, Mar 09, 2014 at 8:35 PM, brpqzme notifications@github.com wrote:There seems to be no way to disable this module. I've disabled it from xposed AND uninstalled it, but it still keeps changing the status bar tint. What can be done?

**Comment by brpqzme** [comment]
Sorry, I should have made it clear. I've rebooted after each step (disable from Xposed, reboot; uninstall APK, reboot). I think flashing the ROM again got rid of it last time, but I just wish there was an easier way.

**Comment by GermainZ** [comment]
Rebooting is definitely enough. If I had to guess, you didn't really uninstall it (e.g. It was a system app and you uninstalled the updates only,) or you rebooted too fast after disabling before the modules list got updated by the Xposed Installer.

**Comment by MohammadAG** [comment]
This module doesn't modify any system files, an uninstall + reboot should be enough to get rid of its changes.
