### ISSUE TITLE
Improper statusbar color detected on low DPI devices

### ISSUE THREAD

**Issue by claytonjn** [MohammadAG/Xposed-Tinted-Status-Bar#22]
I have two devices, a Galaxy S4 and Galaxy Note 10.1. Both run OmniROM nightlies and have almost identical setups, with the exception of a few note-taking apps on the tablet. The S4 DPI is set at 385, while the Note 10.1 is at the default 160. On the Note 10.1, for SOME apps, the auto-detected statusbar color is darker than the action bar color. A good example of this is the Google Play Store: 
![screenshot_2014-03-22-17-13-33](https://f.cloud.github.com/assets/3850252/2491939/752b7528-b207-11e3-9351-7254c8ddc05a.png)

Colors can be set manually and match properly. This does not occur for all apps, I.E. there is no problem with Google Hangouts. 

XDA user sephk posted that for him, the problem came up for any DPI lower than 280.

**Comment by MohammadAG** [comment]
I've seen this on my Nexus 7, I have no idea why it happens to be honest. If I had to, I'd guess there's another layer on the status bar for tablets.

**Comment by claytonjn** [comment]
This may be a coincidence, but the color set by TSB is the same as the color of the line between the actionbar and the rest of the app, highlighted in red here: 
![untitled-1](https://f.cloud.github.com/assets/3850252/2507539/6f919b1a-b3bf-11e3-8984-afce67e79515.png)

That line is visible on both phones and tablets, however.

**Comment by MohammadAG** [comment]
Can you please confirm if this still happens with 1.8.9?

**Comment by claytonjn** [comment]
With 1.8.9 this is no longer happening with the Google Play Store or any other app I have opened on the tablet so far.

**Comment by MohammadAG** [comment]
Fixed in https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/d268b55be68f0f60978f349f48a0188c66ba415b and https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/b6378d581a44e75e5177b549aa21f13787b0dffc
