### ISSUE TITLE
Strange behavior with TSB and XuiMod's BatteryBar

### ISSUE THREAD

**Issue by claytonjn** [MohammadAG/Xposed-Tinted-Status-Bar#23]
Recently, XuiMod was updated with a feature for the BatteryBar to follow the colors of statusbar icons, as set by TSB. Everything is working perfectly with one exception. The defaults I have set in TSB are #00000000 for statusbar and #FFFFFFFF for status icons. If I open an app such as Google Hangouts which has a light statusbar and dark icons, and then go to recents, or home, which should have the default TSB colors, the BatteryBar tint doesn't change. This only occurs when going for dark to light. To test, I set the defaults in TSB so that the statusbar would be #FFFFFFFF and the status icons would be #FF000000 and I went from an app with a dark statusbar and white icons to the recents or home and the BatteryBar darkened properly. 

The strange thing is that I have been able to remedy the issue by setting the default value for status icons in TSB to #FAFFFFFF. Basically, if the statusbar icons change from anything to #FFFFFFFF the BatteryBar doesn't change, but if the statusbar icons go from anything to anything other than #FAFFFFFF the BatteryBar changes every single time. It's not such a big deal because I can just set defaults to #FAFFFFFF and everything looks fine, but my OCD knows that the icons don't match EXACTLY because the alpha isn't FF so it drives me crazy.

I contacted the developer of XuiMod about this first, obviously, as I assumed it was a problem on that end. He wasn't able to figure anything out at all unfortunately. See his reply here: http://forum.xda-developers.com/showpost.php?p=50751267&postcount=782 and here: http://forum.xda-developers.com/showpost.php?p=51155607&postcount=823

**Comment by MohammadAG** [comment]
Those broadcasts are used internally as IPC, this may or may not change in the future, so it might be best not to use them.

As an alternative, listening to the GravityBox intents I send would be best.
https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/blob/master/src/com/mohammadag/colouredstatusbar/ColourChangerMod.java#L503

I'd suggest directing the developer here if there are any issues :)

**Comment by MohammadAG** [comment]
I'm assuming this issue can be closed now as per the commit referenced above :)
If it's not, feel free to reopen it
