### ISSUE TITLE
lock screen activity

### ISSUE THREAD

**Issue by Efreak** [MohammadAG/Xposed-Tinted-Status-Bar#3]
one of the issues listed the xda thread is that transparency dreamt work on the lock screen. it's crossed out, which I assume means it now works. furthermore, it means you know what the activity for this is. can you please share this? I'm getting a bright white bar over the lwp on my lockscreen.

**Comment by MohammadAG** [comment]
There is no lockscreen activity, a workaround was added. I'll push the changes in the new version soon :)
