### ISSUE TITLE
The color of icond in the status bar doesn't change as it should be

### ISSUE THREAD

**Issue by JonathanKang** [MohammadAG/Xposed-Tinted-Status-Bar#31]
I am using miui. The color of icons in the status bar doesn't change according to to color of the app. Only a few icons in the status bar can change its color.

**Comment by MohammadAG** [comment]
I'm not going to support MIUI, I've heard bad horror stories about them for developers, plus I don't have a device with a MIUI ROM so I can't test it.
Ask someone in the MIUI community to send a patch and I'll be happy to merge it.
