### ISSUE TITLE
Gradient over tint (like KK has)

### ISSUE THREAD

**Issue by pasomnica** [MohammadAG/Xposed-Tinted-Status-Bar#34]
I've read somewhere (it was your post on xda) that this feature would be included in next releases.. Many people  requesting this feature on forum, so I'm just asking, if we should really wait for it.

**Comment by MohammadAG** [comment]
I said it may be coming in a future version and that I'll be looking into it, not that it'll be in the next version specifically.

Anyway, you'll find out about any features in commits.

**Comment by pasomnica** [comment]
Thanks ;)

**Comment by MohammadAG** [comment]
This is in 1.8.9, closing issue :)
