### ISSUE TITLE
Battery icon is always changing back to white (KitKat) 

### ISSUE THREAD

**Issue by thech40s** [MohammadAG/Xposed-Tinted-Status-Bar#36]
The battery indicator in status bar will always change back to white after a few seconds (or will stay white and never change color) 
This is on CM11 with GravityBox[KK], but the battery  settings are untouched (except for the cm11 circle battery, which is activated. But it happens with the default battery icon also)

**Comment by GermainZ** [comment]
The following commit might fix this issue.

1437914e5452a7566cd2f3607b79160ffc12ba5f (will be in the next version)

If you still encounter this issue once you get the next version (or compile manually), open another issue and mention the exact ROM you're using.
