### ISSUE TITLE
NavBar on Nexus 7 flo

### ISSUE THREAD

**Issue by TyJoKo** [MohammadAG/Xposed-Tinted-Status-Bar#40]
In landscape mode, the icons don't turn black on lighter colors but they do on portraight with the same conditions. I have changed many settings

**Comment by GermainZ** [comment]
Is this still happening? If so, please give exact steps to reproduce it and mention your ROM/TSB versions.

**Comment by TyJoKo** [comment]
No. I flashed cm m9 and removed Xposed but thankyou.
