### ISSUE TITLE
Clock color doesn't change

### ISSUE THREAD

**Issue by MaestroDeSwag** [MohammadAG/Xposed-Tinted-Status-Bar#41]
I'm on a galaxy s4 running hyperdrive rls16, and the color of the clock doesn't change, regardless of the status bar color. The notification icons darken, but the clock, Wi-Fi, and battery icons remain white, making them extremely hard to read.

**Comment by GermainZ** [comment]
The following commit should fix this issue: b2beb7944f44d874776131b6178063c3879add33 (already in 1.8.9.3)
