### ISSUE TITLE
Black NavBar on Z1.757

### ISSUE THREAD

**Issue by Elfeno** [MohammadAG/Xposed-Tinted-Status-Bar#42]
The nav bar stay black even on lockscreen wich is pretty ugly. After a lot of unactivation separate xposed modules it's appear that this issue happen due to SERAJR mod but it doesnt have any option that about navbar (only touch color but the issue still without the whole theme ui category activated )  Thanks to you if you can give a look :)

**Comment by MohammadAG** [comment]
This would be better suited as a bug report for SERAJR, the module works fine in my Z1.
