### ISSUE TITLE
battery procentage is always white at s4

### ISSUE THREAD

**Issue by prologikus** [MohammadAG/Xposed-Tinted-Status-Bar#44]
At i9505 the color of the battery % fron the statusbar doesn't change
![screenshot_2014-06-08-21-12-26](https://cloud.githubusercontent.com/assets/7831851/3211916/7d92d954-ef38-11e3-9cbd-b73ebbf9e98e.png)

**Comment by MohammadAG** [comment]
This has already been fixed in upstream. It'll be in the next version.

https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/83faf31007df4cf336da8684b7b2ef6738d90588
