### ISSUE TITLE
1.8.9 doesn't work on miui

### ISSUE THREAD

**Issue by JonathanKang** [MohammadAG/Xposed-Tinted-Status-Bar#49]
The color of status bar doesn't change at all!

**Comment by MohammadAG** [comment]
I'm assuming it worked before? If so, 1.8.9.1 may fix it.

**Comment by JonathanKang** [comment]
If I tick the 'Show a gradient over tint' option, it doesn't work. But if the option is not selected, it works well.
Another problem is that it cannot tint all the icons of the status bar of MIUI rom. Can you solve this problem?

**Comment by MohammadAG** [comment]
I can't support MIUI myself, I'd need a patch from a dev who uses MIUI.

**Comment by JonathanKang** [comment]
A patch? What's that? I'm willing to help if I can do something that is helpful.

**Comment by MohammadAG** [comment]
A code patch, changes in code.

Also as I said, 1.8.9.1 may fix your issue since it also affected Samsung devices.

**Comment by JonathanKang** [comment]
OK. I'll wait for the version 1.8.9.1. If it still doesn't work, I'd like to patch it. Thanks a lot for your awesome job!

**Comment by MohammadAG** [comment]
It's already on the repo.

**Comment by JonathanKang** [comment]
I tried the version 1.8.9.1, and gradient worked perfectly. Still not all the icons of the status bar can change color, so I'm gonna work on it.

**Comment by JonathanKang** [comment]
I wanna patch the code to make it work perfectly on miui. Any suggestion? Such as which files to patch or general way to do it. Thx. @MohammadAG

**Comment by GermainZ** [comment]
#### How to make a patch:
- See what's not working by looking at the logs.
- Understand why it's not working, possibly by decompiling the relevant framework files.
- Try to fix it, if it's possible without major changes.
- If not possible, abandon MIUI.

#### How to take a shortcut and not have to make a patch:
- Abandon MIUI.

If you're asking for a more detailed tutorial, I'm afraid you're on your own… ;)

**Comment by MohammadAG** [comment]
Closed as per https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/pull/73
