### ISSUE TITLE
traffic color dose not change

### ISSUE THREAD

**Issue by 32tian** [MohammadAG/Xposed-Tinted-Status-Bar#50]
My device is nexus 5 and I am running Mahdi rom now,using the last released version 1.8.9.1.

**Comment by MohammadAG** [comment]
Fixed in https://github.com/MohammadAG/Xposed-Tinted-Status-Bar/commit/38d4a6f9db52cc3ce77cdd08c7a738cce7089b97

Wait for the next version.
