### ISSUE TITLE
Broken on Cyanogenmod 11 M7 and higher

### ISSUE THREAD

**Issue by Blaziken584** [MohammadAG/Xposed-Tinted-Status-Bar#53]
Cyanogenmod 11 M7 changed how the status bar and navbar works, and so they are no longer affected by it and it completely does nothing. I've tried the most recent experimental of 1.8.9.2 I believe it was and still no luck.  With expanded desktop on the navbar no longer abides by KitKat's translucency, and is instead a translucent black, and same with the status bar.  I've also tried it with expanded desktop off and it's as if I hadn't even installed this Xposed module.

**Comment by GermainZ** [comment]
Works here on the latest nightlies. Are you assuming that M7 changed how the status bar works, or is that based on actual commits?

Anyway, you probably want to double check that TSB is enabled. If so, provide logs.

**Comment by Blaziken584** [comment]
I feel very dumb now haha.  I checked my Xposed, and it had turned out to need an update after I flashed to M7/ the 6/06 nightly I am now on.  I'm usually not like to forget to check the simple fixes first, sorry for wasting your time but thank you for the quick response, as it fixed the problem anyway =)
