### ISSUE TITLE
Question&Issue

### ISSUE THREAD

**Issue by tommyvct** [MohammadAG/Xposed-Tinted-Status-Bar#58]
First of all, I'm just a Chinese student, and my English is  VERY POOR, so Please NEVERMIND the grammar&words errors!

My device is HTC Desire 300, Sense 5.0, A4.1.2

Here's the question:
Why the status bar in any app is like 4.4, which like the launcher on 4.4, gradient from black to trans? I think is too ugly! And the PURE COLOR&TRANS(like iOS7) is what I want! So, can you make an easy-understand switch to this? Thankyou VERY MUCCCCCCHHHHHHHH!!!!!!!!!!!!!!

And here's a  issue:
In Ver. 1.8.5, the module is NOT COMPATIBLE with Gravity Box at all though I did NOTHING with GB! When they be used together, the launcher's status bar is BLACK. Then I enter app#1 from launcher, the #1's status bar was SHOWN as LAUNCHER'S! And #2's will be SHOWN as #1'S!

At the end, thanks to all the developer who working for Xposed! Without Xposed, I can't use my device well!

PS: What's the meanning of Mohammad? Or just a name? It seems that most of Arabians I have seen are use this 1st(last?) name, which just like most Chinese use 李(Li) as their last name! I think it is interesting!

**Comment by GermainZ** [comment]
There's an option on the preferences to disable or enable the gradient, use it.
Manually set the color of the status bar to #00000000 for your launcher.
Google "Mohammad" (or use whatever search engine you like).
