### ISSUE TITLE
Google Keep

### ISSUE THREAD

**Issue by Avamander** [MohammadAG/Xposed-Tinted-Status-Bar#64]
Software: CM11 by Varcain, TSB 1.8.9.3, Xposed 2.6.1
Bug: Google Keep does not tint properly
![2014-06-28 16 58 08](https://cloud.githubusercontent.com/assets/5392141/3421321/9408439c-fee5-11e3-9217-1af2395e46a2.png)

**Comment by AudioLaboratories** [comment]
I've been trying to find a solution to this for a long time now. Please fix this!

**Comment by ariririos** [comment]
I have the same problem, and I noticed that it fixes itself once you open the panel on the side.

**Comment by Avamander** [comment]
But it should be fixed from the start

**Comment by ariririos** [comment]
I found the problem-the action bar is translucent, so the action bar color is slightly lighter than the one the app knows about. Here's a picture (you can see the menu underneath the action bar)
![screenshot_2014-08-05-15-15-49](https://cloud.githubusercontent.com/assets/6045595/3817155/5d776228-1cd5-11e4-938e-8bd449147d08.png)
