### ISSUE TITLE
Status Bar is transparent with standard settings

### ISSUE THREAD

**Issue by ghost** [MohammadAG/Xposed-Tinted-Status-Bar#65]
without TintedStatusBar:
https://www.dropbox.com/s/fnqmoyokmo1sofc/ohneTintedBar.png

with TintedStatusBar:
https://www.dropbox.com/s/131vht1kv7lriam/mitTintedBar.png

I had installed Xposed Framework and TintedStatusBar on my CyanogenMod.
TintedStatusBar had worked perfect. Then I changed the color of Android-System in per app tints to opacity = 0. I rebooted the system and there was the issue. I removed Xposed Framework and TintedStatusBar from my system and the issue was away. But then, after a reinstallation it was again there, with standard settings. So always when I have TintedStatusBar installed, there is this bad issue. Can you please help me?
Sorry for my bad english, I am german.

**Comment by GermainZ** [comment]
Links are dead. I'm guessing you just need to set the colors manually for that particular app. Anyway, please don't use the issue tracker for general support, post in the XDA thread for that where you're more likely to get help.
