### ISSUE TITLE
Change GoogleNow colors problem

### ISSUE THREAD

**Issue by Kucharskov** [MohammadAG/Xposed-Tinted-Status-Bar#68]
That's repost from module XDA theard:
Here any way to change colors of status, navbar! I dunno why.
![googlenow](https://cloud.githubusercontent.com/assets/2500114/3427920/92fd84d0-0039-11e4-8e63-8d920f36a110.png)

P.S Sorry for my bad english :(

**Comment by GermainZ** [comment]
Just set the color manually.

**Comment by Kucharskov** [comment]
When i set it manually - that's doesn't work.

**Comment by GermainZ** [comment]
How are you setting it? Try enabling the debug logging and toast activity titles options, too (and read what shows on your screen).

**Comment by SujayShinoda** [comment]
I have this glitch too. Initially the colour stays black but after opening a news topic the status bar changes to defined colour, again while exiting it turns black as in the picture above.

EDIT: 

Looked it up, it's 'com.google.android.velvet.ui.activity.', Iv'e it's set it to white, the activity launches but the colour remains black.

In fact I just checked all the activities and all of em are set to white. So this is something only the developer can fix.

**Comment by GermainZ** [comment]
I can't reproduce this. Any particular way to make it happen?
