### ISSUE TITLE
GooglePlay books statusbar icon color

### ISSUE THREAD

**Issue by Kucharskov** [MohammadAG/Xposed-Tinted-Status-Bar#69]
That's repost from module XDA theard:
Here's sth strange somtime icons are black, somotimes are white! Yours checking system are wrong or bad? I think here best color is white. Maybe you will check your color changing system?
![googleplay](https://cloud.githubusercontent.com/assets/2500114/3427930/b3ca76be-0039-11e4-98a2-a0596514cf42.png)

BTW. What are you thing about that: When the icons must be colored to "black" - most effecienlt will be add black 1px contour without changing color. Or you need come up with a system which can change only white to black and black to white piksels. Then inside battery icon we can see green or red fulfillment.

P.S Sorry for my bad english :(

**Comment by GermainZ** [comment]
Set the color manually. As for your suggestion, that would be painfully inefficient and makes no sense - the whole icon should be tinted, that's the point of using this module.
That being said, a mask is used to tint the icons. If you think a different mask might suit you better, you can try that.
