### ISSUE TITLE
How to build it myself?

### ISSUE THREAD

**Issue by ArturGaspar** [MohammadAG/Xposed-Tinted-Status-Bar#7]
How do I build the Tinted Status Bar module myself, from the sources? What libraries do I need?

**Comment by GermainZ** [comment]
XposedBridgeApi, HoloColorPicker, ListViewAnimations. Could've found that out by actually reading the build output :)

**Comment by ArturGaspar** [comment]
Sorry, I was getting errors with HoloColorPicker. I see they are fixed in commit 925cbd7.
