### ISSUE TITLE
Battery icon not coloured on ParanoidAndroid 4.4

### ISSUE THREAD

**Issue by ackwell** [MohammadAG/Xposed-Tinted-Status-Bar#75]
As of the addition of theme engine support for the status bar battery icon in AOSP4.4, Tinted status bar no longer seems to be able to tint it. 
Pictures related. 
Black
![screenshot_2014-07-02-17-16-37](https://cloud.githubusercontent.com/assets/534235/3453153/3a93dafa-01c0-11e4-9951-5e5dc3fff69c.png)
White
![screenshot_2014-07-02-17-16-44](https://cloud.githubusercontent.com/assets/534235/3453155/3fa76732-01c0-11e4-8c38-fdce5e4a96a4.png)

**Comment by mhmdmodan** [comment]
Confirmed in CM11

![screenshot_2014-07-07-15-47-53 2](https://cloud.githubusercontent.com/assets/7477482/3503027/a7b16ce8-0629-11e4-8614-eff0f2781a65.jpg)

**Comment by LiquidPL** [comment]
PA 4.4.2 here, in my case the clock is also not coloured.
![screenshot_2014-07-10-23-09-31](https://cloud.githubusercontent.com/assets/991831/3545449/c99c7e52-0876-11e4-9492-a727a4aeefd1.png)

**Comment by mhmdmodan** [comment]
Are you running gravity box? If I install gravity box my clock becomes
white as well.

**Comment by LiquidPL** [comment]
Yeah, after disabling gravitybox clock turned black. However, while it was still enabled, changing phone orientation from portrait to landscape (and the other way) makes the clock change its color.

**Comment by derioz** [comment]
One annoying bug.

**Comment by GermainZ** [comment]
The following commits should fix these issues.

Clock: b2beb7944f44d874776131b6178063c3879add33 (already in 1.8.9.3)
Battery: 1437914e5452a7566cd2f3607b79160ffc12ba5f (will be in the next version)

If you still encounter this issue once you get the next version (or compile manually), open another issue and mention the exact ROM you're using.
