### ISSUE TITLE
TSB crash

### ISSUE THREAD

**Issue by Grand1** [MohammadAG/Xposed-Tinted-Status-Bar#76]
Hi, there.

I can not enter into the TSB settings. 
Tap on Settings Icon on TSB main screen brings popup "Unfortunately, Tinted Transfluent Status bar has stopped." And there is "Ok" only.

Nexus 5 4.4.4, ROM -stock, franco kernel v.55
Xposed v.2.6.1 
GravityBox(kk) v.3.2.1.
neXtLauncher v.3.13 

Thanks in advance

**Comment by MohammadAG** [comment]
That's a different module.
