### ISSUE TITLE
Incompatibility with Gravitybox

### ISSUE THREAD

**Issue by tajnymag** [MohammadAG/Xposed-Tinted-Status-Bar#78]
Hi, I have latest BETA release of TSB and Gravitybox imstalled. TSB Works perfectly (in many Apps) but if I enable GB both modules try to change color of statusbar and the conclusion is mixed color (fex. black

**Comment by MohammadAG** [comment]
Enable status bar icon colours in GravityBox. TSB is fully compatible with GB.

**Comment by tajnymag** [comment]
from GB + white from TSB = grey) I'm running stock 4.1.2 on Galaxy S2.

**Comment by tajnymag** [comment]
https://www.dropbox.com/s/vvlnkw79f6sd7mi/Screenshot_2014-07-05-07-52-04.png

**Comment by tajnymag** [comment]
I her this: https://www.dropbox.com/s/nmizrc3xik3btx4/Screenshot_2014-07-05-08-08-35.png

Instead of this: https://www.dropbox.com/s/wfe3gw0vbk1g928/Screenshot_2014-07-05-08-10-02.png

**Comment by MohammadAG** [comment]
Disable transparency management in GravityBox.

**Comment by tajnymag** [comment]
Thank you. Looks like it work.

**Comment by deathlink445** [comment]
Hi. I have SGS3 mini and I have an issue.
I have TSB and GB, and when I try to change battery style or replace the clock in GB, nothing works.
Is there a way that TSB blocking it?
