### ISSUE TITLE
Status icons not showing related info

### ISSUE THREAD

**Issue by notpushkin** [MohammadAG/Xposed-Tinted-Status-Bar#8]
Battery and network icons are always full, which makes them pretty useless. Here's a screenshot:

![tmp_1521839481](https://f.cloud.github.com/assets/1298948/1748305/bfd8cc96-64b0-11e3-918e-fc00347abae3.png)

**Comment by GermainZ** [comment]
That's how the current filter works. Use transparent icons (with e.g. GravityBox or XBlast Tools) to 'fix' it.

**Comment by notpushkin** [comment]
Okay, I suppose it's okay then.
