### ISSUE TITLE
Clock and Battery Icon

### ISSUE THREAD

**Issue by tad1073-zz** [MohammadAG/Xposed-Tinted-Status-Bar#80]
When the clock is moved to the center of the statusbar it stays white and the same goes for the battery icon when changing to different style.

**Comment by varemenos** [comment]
:+1:

**Comment by PwnicornDev** [comment]
Not sure this is the same bug, but for me the battery indicator is always white on CM11:
![image](https://cloud.githubusercontent.com/assets/3987812/3711659/79c3db68-14e3-11e4-93c2-5a94065a0a60.png)

**Comment by GermainZ** [comment]
The following commits should fix these issues.

Clock: b2beb7944f44d874776131b6178063c3879add33 (already in 1.8.9.3)
Battery: 1437914e5452a7566cd2f3607b79160ffc12ba5f (will be in the next version)

If you still encounter this issue once you get the next version (or compile manually), open another issue and mention the exact ROM you're using.
