### ISSUE TITLE
incompitability

### ISSUE THREAD

**Issue by nish5** [MohammadAG/Xposed-Tinted-Status-Bar#81]
Lots of apps are yet incompitible like bbm tubemate  etc . Please add support to all alls

**Comment by GermainZ** [comment]
Just configure them manually.

**Comment by nish5** [comment]
I tried but i din get the exact color can you tell me the color code for
tubemate and bbm ?

**Comment by GermainZ** [comment]
You can use the notification color picker.

**Comment by nish5** [comment]
How to access it ?

**Comment by GermainZ** [comment]
Just like everything else - open TSB's settings, move your eyeballs up and down while scrolling, keep going till you find it.
Once you do, it should be pretty self explanatory, I hope.

**Comment by nish5** [comment]
Got it thanks
