### ISSUE TITLE
Transparent background displays black instead of the wallpaper

### ISSUE THREAD

**Issue by varemenos** [MohammadAG/Xposed-Tinted-Status-Bar#83]
Shouldn't setting the background color of the status bar display the area of the wallpaper that's below the status bar if the opacity of the background color is set to 0? Because in my phone, it's black

**Comment by MohammadAG** [comment]
The app itself needs to draw behind the status bar.

**Comment by varemenos** [comment]
What's the point of asking for the alpha channel then?

**Comment by MohammadAG** [comment]
For said apps that draw behind the status bar?
