### ISSUE TITLE
Keyboard navbar color

### ISSUE THREAD

**Issue by omeryagmurlu** [MohammadAG/Xposed-Tinted-Status-Bar#86]
I want to make swiftkey keyboards navbar color "13436B" . I set Swiftkey's all activity's navbar to this and I disable linking status bar but it doesnt work. what should I do? Sorry for english

Current
http://i.imgur.com/L1XkbBP.png

"I want it to look like this (I made it on paint.net)
http://i.imgur.com/47G3Wh9.png

**Comment by GermainZ** [comment]
TSB > Default settings > Navigation Bar Tint (IM)

Please don't use the issue tracker for general support in the future.
