### ISSUE TITLE
Option to automatically set status bar color to touch/general color

### ISSUE THREAD

**Issue by ariririos** [MohammadAG/Xposed-Tinted-Status-Bar#89]
There should be a setting to automatically set the status bar color to the touch or the general color (those colors shown when you open the notifications from enabling the notification color picker), in the same way that the module auto-detects the color to use from the action bar's color. Such a setting would be a great help in getting the right color when an app doesn't have an action bar or the action bar color can vary, like in the Google search app, Timely, and ES file explorer.

**Comment by GermainZ** [comment]
This won't happen. The notification color picker is basically taking a screenshot every time you open a new activity. Doing that for every activity (or even select activities) is a resource hog and drains battery.
