### ISSUE TITLE
Lock Screen mismatch on Jelly Bean

### ISSUE THREAD

**Issue by saurabhv13** [MohammadAG/Xposed-Tinted-Status-Bar#90]
I am using Jelly Bean 4.2.1 and status bar has been made transparent using gravity box, but it looks weird on shaded lockscreen. (Screenshot given).

Please inform how lockscreen status bar can also be made of same shade as that of lock screen ?
![screenshot_2014-07-27-21-37-01](https://cloud.githubusercontent.com/assets/8276487/3714445/e65993c4-15a8-11e4-9ab5-44980bed28f2.png)

I want uniform shade across lockscreen.

Regards.

P.S.: I am not a programmer and want solution in simple terms, which can be kind of plug n play.

**Comment by MohammadAG** [comment]
This isn't a place to get help on other modules, it seems like you don't use TSB at all.

Please use GravityBox's thread.

**Comment by saurabhv13** [comment]
I am sorry, but I love TSB and can't imagine my mobile without it. I tried
after disabling Gravity Box but status bar remains without shade and lock
screen remains shaded.

Please help to create uniform lock screen across the screen.

Regards,
