### ISSUE TITLE
White clock and battery

### ISSUE THREAD

**Issue by achook** [MohammadAG/Xposed-Tinted-Status-Bar#93]
Clock and battery is often white. 

![screenshot_2014-07-29-20-28-48](https://cloud.githubusercontent.com/assets/8215833/3739977/5a5cebf6-1750-11e4-96bc-db782158c52c.png)
![screenshot_2014-07-29-20-31-30](https://cloud.githubusercontent.com/assets/8215833/3739958/22dc1224-1750-11e4-8deb-ceaec67e2f35.png)
![screenshot_2014-07-29-20-24-22](https://cloud.githubusercontent.com/assets/8215833/3739965/3126867a-1750-11e4-9540-16bb35dcd8a9.png)

**Comment by achook** [comment]
Log: http://pastebin.com/J88MC7Y3

**Comment by gcq** [comment]
Have the same issue with the battery icon only.

**Comment by GermainZ** [comment]
The following commits should fix these issues.

Clock: b2beb7944f44d874776131b6178063c3879add33 (already in 1.8.9.3)
Battery: 1437914e5452a7566cd2f3607b79160ffc12ba5f (will be in the next version)

If you still encounter this issue once you get the next version (or compile manually), open another issue and mention the exact ROM you're using.
