### ISSUE TITLE
Default tint has no option for stock homescreen like tint

### ISSUE THREAD

**Issue by SujayShinoda** [MohammadAG/Xposed-Tinted-Status-Bar#95]
When I change the default tint, it has no gradient option. Like translucent black to transparent gradient in statusbar. I used other modules for this effect but this mod eventually overrides them, so an option to turn off default tint so it doesn't interfere with other mods would be just fine. I'm on most recent beta.

**Comment by MohammadAG** [comment]
Set the tint to 66000000, read the XDA thread.
